### ISSUE TITLE
LinkedIn Integration Throwing "undefined method" Error

### ISSUE THREAD

**Issue by rdlauer** [orbit-love/community-ruby-linkedin-orbit#22]
Hi - our LinkedIn + Orbit integration has been working well for months, but now in the last few days it's throwing a new error (and we did recently go through the developer portal renewal process, so I don't think it's an auth issue):

```
Run linkedin_orbit --check-comments
  linkedin_orbit --check-comments
  shell: /usr/bin/bash -e {0}
  env:
    LINKEDIN_ORGANIZATION: ***
    LINKEDIN_TOKEN: ***
    ORBIT_API_KEY: ***
    ORBIT_WORKSPACE_ID: ***
Checking for new LinkedIn comments and posting them to your Orbit workspace...
/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/linkedin_orbit-0.5.1/lib/linkedin_orbit/linkedin.rb:91:in `get_posts': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/linkedin_orbit-0.5.1/lib/linkedin_orbit/linkedin.rb:13:in `process_comments'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/linkedin_orbit-0.5.1/lib/linkedin_orbit/client.rb:65:in `comments'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/linkedin_orbit-0.5.1/scripts/check_comments.rb:13:in `render'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/linkedin_orbit-0.5.1/bin/linkedin_orbit:31:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/linkedin_orbit:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/linkedin_orbit:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by colinloretz** [comment]
@rdlauer Hi Rob, there was an update that we rolled out. We have it running properly for other workspaces so I'll look into what edge cases you might be hitting with the new version.

If you'd like to set it back to the old version, you can update your yaml file for the github actions to use a specific version:
`gem install --no-document linkedin_orbit -v 0.3.0`

[0.3.0 was the version](https://rubygems.org/gems/linkedin_orbit) before I changed anything.

I actually just realized that this doesn't check to see if the LinkedIn token has expired. The tokens will only be valid for about 30 days at which point they will need to be renewed. As you mentioned, you went through that recently but I'll go ahead and add some better error handling for that.

**Comment by rdlauer** [comment]
Thanks I'll try that!
